name = "fendy"
description = "A simple theme for Hugo. That's it."
features = ["blog", "shortcode", "syntax Highlighting"]
homepage = "https://github.com/wrentreeco/fendy/"
license = "MIT"
licenselink = "https://github.com/wrentreeco/fendy/blob/master/LICENSE.md"
min_version = 0.90
tags = [
  "blog",
  "clean",
  "customizable",
  "dark",
  "highlighting",
  "light",
  "minimal",
  "monochromatic",
  "multilingual",
  "personal",
  "responsive",
  "simple",
  "technical",
]
